constexpr auto tiles_json = R"({
  "tiles0": {
    "00": { "name": "fblock", "texture": "tile0", "solid": false },
    "01": { "name": "ftile-neg", "texture": "tile1", "solid": false },
    "02": { "name": "ftile", "texture": "tile2", "solid": false },
    "03": { "name": "fchecker", "texture": "tile3", "solid": false },
    "04": { "name": "fchecker-light", "texture": "tile4", "solid": false },
    "05": { "name": "fchecker-small-dark", "texture": "tile5", "solid": false },
    "06": { "name": "wsolid0", "texture": "tile6", "solid": true },
    "07": { "name": "wsolid1", "texture": "tile7", "solid": true },
    "08": { "name": "wsolid2", "texture": "tile8", "solid": true },
    "09": { "name": "wsolid3", "texture": "tile9", "solid": true },
    "10": { "name": "fcarpet0", "texture": "tile10", "solid": false },
    "11": { "name": "fcarpet1", "texture": "tile11", "solid": false },
    "12": { "name": "fcarpet2", "texture": "tile12", "solid": false },
    "13": { "name": "fchecker-small", "texture": "tile13", "solid": false },
    "14": { "name": "fchecker-small-light", "texture": "tile14", "solid": false },
    "15": { "name": "fpenta", "texture": "tile17", "solid": false },
    "16": { "name": "fcracked-n", "texture": "tile20", "solid": false },
    "17": { "name": "fcracked-e", "texture": "tile21", "solid": false },
    "18": { "name": "fstripped-back", "texture": "tile22", "solid": false },
    "19": { "name": "fstripped", "texture": "tile23", "solid": false },
    "20": { "name": "fwood-e", "texture": "tile24", "solid": false },
    "21": { "name": "fwood-n", "texture": "tile25", "solid": false },
    "22": { "name": "fgrass0", "texture": "tile26", "solid": false },
    "23": { "name": "fgrass1", "texture": "tile27", "solid": false },
    "24": { "name": "fgrass2", "texture": "tile28", "solid": false },
    "25": { "name": "fgrass3", "texture": "tile29", "solid": false },
    "26": { "name": "w-alt-n", "texture": "tile30", "solid": true },
    "27": { "name": "w-alt-e", "texture": "tile31", "solid": true },
    "28": { "name": "w0-n", "texture": "tile70", "solid": true },
    "29": { "name": "w0-e", "texture": "tile71", "solid": true },
    "30": { "name": "w0-w", "texture": "tile72", "solid": true },
    "31": { "name": "w0-s", "texture": "tile73", "solid": true },
    "32": { "name": "w0-nw", "texture": "tile52", "solid": true },
    "33": { "name": "w0-ne", "texture": "tile53", "solid": true },
    "34": { "name": "w0-sw", "texture": "tile62", "solid": true },
    "35": { "name": "w0-se", "texture": "tile63", "solid": true },
    "36": { "name": "w1-n", "texture": "tile80", "solid": true },
    "37": { "name": "w1-e", "texture": "tile81", "solid": true },
    "38": { "name": "w1-w", "texture": "tile82", "solid": true },
    "39": { "name": "w1-s", "texture": "tile83", "solid": true },
    "40": { "name": "w1-nw", "texture": "tile50", "solid": true },
    "41": { "name": "w1-ne", "texture": "tile51", "solid": true },
    "42": { "name": "w1-sw", "texture": "tile60", "solid": true },
    "43": { "name": "w1-se", "texture": "tile61", "solid": true },
    "44": { "name": "w2-n", "texture": "tile74", "solid": true },    
    "45": { "name": "w2-e", "texture": "tile75", "solid": true },
    "46": { "name": "w2-w", "texture": "tile76", "solid": true },
    "47": { "name": "w2-s", "texture": "tile77", "solid": true },
    "48": { "name": "w2-nw", "texture": "tile56", "solid": true },
    "49": { "name": "w2-ne", "texture": "tile57", "solid": true },
    "50": { "name": "w2-sw", "texture": "tile66", "solid": true },
    "51": { "name": "w2-se", "texture": "tile67", "solid": true },
    "52": { "name": "w3-n", "texture": "tile90", "solid": true },
    "53": { "name": "w3-w", "texture": "tile91", "solid": true },
    "54": { "name": "w3-e", "texture": "tile92", "solid": true },
    "55": { "name": "w3-s", "texture": "tile93", "solid": true },
    "56": { "name": "w3-nw", "texture": "tile54", "solid": true },
    "57": { "name": "w3-ne", "texture": "tile55", "solid": true },
    "58": { "name": "w3-sw", "texture": "tile64", "solid": true },
    "59": { "name": "w3-se", "texture": "tile65", "solid": true }
},

"player": {
    "player-down0":     { "texture": "tile0", "solid": true },
    "player-left0":     { "texture": "tile1", "solid": true },
    "player-up0":       { "texture": "tile2", "solid": true },
    "player-right0":    { "texture": "tile3", "solid": true },
    "player-down1":     { "texture": "tile10", "solid": true },
    "player-left1":     { "texture": "tile11", "solid": true },
    "player-up1":       { "texture": "tile12", "solid": true },
    "player-right1":    { "texture": "tile13", "solid": true },
    "player-down2":     { "texture": "tile20", "solid": true },
    "player-left2":     { "texture": "tile21", "solid": true },
    "player-up2":       { "texture": "tile22", "solid": true },
    "player-right2":    { "texture": "tile23", "solid": true },
    "health":           { "texture": "tile40", "solid": true },
    "sanity":           { "texture": "tile41", "solid": true }
},

"objects0": {
    "door0-n":          { "texture": "tile0", "solid": true },
    "door0-e":          { "texture": "tile1", "solid": true },
    "door0-w":          { "texture": "tile2", "solid": true },
    "door0-s":          { "texture": "tile3", "solid": true },
    "door0-n-open":     { "texture": "tile10", "solid": false },
    "door0-e-open":     { "texture": "tile11", "solid": false },
    "door0-w-open":     { "texture": "tile12", "solid": false },
    "door0-s-open":     { "texture": "tile13", "solid": false },
    "door1-n":          { "texture": "tile5", "solid": true },
    "door1-e":          { "texture": "tile6", "solid": true },
    "door1-w":          { "texture": "tile7", "solid": true },
    "door1-s":          { "texture": "tile8", "solid": true },
    "door1-n-open":     { "texture": "tile15", "solid": false },
    "door1-e-open":     { "texture": "tile16", "solid": false },
    "door1-w-open":     { "texture": "tile17", "solid": false },
    "door1-s-open":     { "texture": "tile18", "solid": false },
    "door2-n-open":     { "texture": "tile20", "solid": false },
    "door2-e-open":     { "texture": "tile21", "solid": false },
    "door2-w-open":     { "texture": "tile22", "solid": false },
    "door2-s-open":     { "texture": "tile23", "solid": false }
}

})";
